plugins:
  - "./plugins/plugin.js"

# Allows to replace a $ref with `type: object` in order to avoid infinite loops
# when Redocly attempts to render circular references.
decorators:
  plugin/circular-patch:
    verbose: false
    schemas:
      Address:
        - Customer
      Cart:
        - Customer
        - Order
        - Payment
        - PaymentSession
      ClaimImage:
        - ClaimItem
      ClaimItem:
        - ClaimOrder
      ClaimOrder:
        - Fulfillment
        - Order
        - Return
      Country:
        - Region
      Customer:
        - Order
      CustomerGroup:
        - Customer
        - PriceList
      Discount:
        - Discount
      DiscountRule:
        - DiscountCondition
      DraftOrder:
        - Cart
        - Order
      Fulfillment:
        - ClaimOrder
        - Order
        - Swap
      FulfillmentItem:
        - Fulfillment
      GiftCard:
        - Order
      GiftCardTransaction:
        - GiftCard
        - Order
      LineItem:
        - Cart
        - ClaimOrder
        - Order
        - OrderEdit
        - Swap
      LineItemAdjustment:
        - LineItem
      LineItemTaxLine:
        - LineItem
      MoneyAmount:
        - PriceList
        - ProductVariant
        - Region
      Notification:
        - Notification
      Order:
        - Cart
        - ClaimOrder
        - Customer
        - DraftOrder
        - Fulfillment
        - OrderEdit
        - Payment
        - Refund
        - Return
        - Swap
      OrderEdit:
        - Order
      OrderItemChange:
        - OrderEdit
      Payment:
        - Cart
        - Order
        - Swap
      ProductCategory:
        - ProductCategory
        - Product
      ProductCollection:
        - Product
      ProductOption:
        - Product
      ProductOptionValue:
        - ProductOption
        - ProductVariant
      ProductVariant:
        - Product
      ProductVariantInventoryItem:
        - ProductVariant
      Refund:
        - Order
        - Payment
      Return:
        - ClaimOrder
        - Order
        - Swap
      ReturnItem:
        - Return
      ReturnReason:
        - ReturnReason
      SalesChannelLocation:
        - SalesChannel
      ShippingMethod:
        - Cart
        - ClaimOrder
        - Order
        - Payment
        - Return
        - Swap
      ShippingMethodTaxLine:
        - ShippingMethod
      ShippingOption:
        - Region
      ShippingOptionRequirement:
        - ShippingOption
      ShippingProfile:
        - Product
        - ShippingOption
      Swap:
        - Cart
        - Fulfillment
        - Order
        - Payment
        - Return
      TaxRate:
        - Region
      TrackingLink:
        - Fulfillment

# Similar config to /www/docs/docusaurus.config.js > redocusaurus
# Allows to emulate rendering of API public documentation when using `yarn redocly preview-docs openapi.yaml`
theme:
  openapi:
    theme:
      colors:
        primary:
          dart: "#242526"
      sidebar:
        width: "250px"
    disableSearch: true
    expandResponses: "200,204"
    generatedPayloadSamplesMaxDepth: 4
    hideDownloadButton: true
    hideRequestPayloadSample: true
    nativeScrollbars: true
    requiredPropsFirst: true
    showObjectSchemaExamples: true
    sortTagsAlphabetically: true
