name: Medusa Pipeline
on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      chunks: ${{ steps.set-chunks.outputs.chunks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Assert changed
        run: ./scripts/assert-changed-files-actions.sh "packages"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - id: set-chunks
        name: Set Chunks
        working-directory: integration-tests/modules
        run: echo "chunks=$(yarn run jest --listTests --json | jq -cM '[_nwise(length / 3 | ceil)]')" >> $GITHUB_OUTPUT

      - id: set-matrix
        name: Set Chunk IDs
        run: echo "matrix=$(echo $CHUNKS | jq -cM 'to_entries | map(.key)')" >> $GITHUB_OUTPUT
        env:
          CHUNKS: ${{ steps.set-chunks.outputs.chunks }}

  unit-tests:
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Assert changed
        run: ./scripts/assert-changed-files-actions.sh "packages"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - name: Build Packages
        run: yarn build

      - name: Run unit tests
        run: yarn test

  integration-tests-packages:
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - name: Build Packages
        run: yarn build

      - name: Run integration tests
        run: yarn test:integration:packages
        env:
          DB_PASSWORD: postgres
          DB_USERNAME: postgres

  integration-tests-api:
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - name: Build Packages
        run: yarn build

      - name: Run integration tests
        run: yarn test:integration:api
        env:
          DB_PASSWORD: postgres
          DB_USERNAME: postgres

  integration-tests-plugins:
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - name: Build Packages
        run: yarn build

      - name: Run plugin integration tests
        run: yarn test:integration:plugins
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          NODE_OPTIONS: "--max_old_space_size=4096"

  integration-tests-modules:
    needs: setup
    name: Shard (${{ matrix.chunk }}) Module Integration Tests
    strategy:
      matrix:
        chunk: ${{ fromJSON(needs.setup.outputs.matrix) }}
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - name: Build Packages
        run: yarn build

      - name: Run Modules integration tests
        run: yarn test:integration:modules
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          NODE_OPTIONS: "--max_old_space_size=4096"
          CHUNK: ${{ matrix.chunk }}
          CHUNKS: ${{ needs.setup.outputs.chunks }}

  integration-tests-repositories:
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: pipeline

      - name: Run repository integration tests
        run: yarn test:integration:repositories
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
