# Checks if the announcement bar info was last edited more than 6 days ago, and if so removes it
name: Remove Docs Release Announcement Bar (v1)
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  remove-announcement:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REFERENCE_PAT }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "v1.x"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: docs-remove-announcement

      - name: Install Workspace dependencies
        run: yarn install
        working-directory: docs-util

      - name: Build Workspace packages
        run: yarn build
        working-directory: docs-util

      - name: Remove Announcement Bar
        run: yarn generate:announcement --expire
        working-directory: docs-util/packages/scripts

      - name: Generate Changeset
        run: "yarn generate:changeset"
        working-directory: docs-util/packages/scripts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(docs): Removed Docs Announcement Bar (automated)"
          base: "v1.x"
          title: "chore(docs): Removed Docs Announcement Bar (automated)"
          labels: "type: chore"
          add-paths: www/apps/docs/**
          branch: "docs/remove-announcement"
          branch-suffix: "timestamp"
