name: Generate Docs Release Announcement Bar
on: 
  release:
    types: [published]

jobs:
  add-announcement:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.REFERENCE_PAT }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: docs-release

      - name: Build Packages
        run: yarn build

      - name: Generate Announcement Bar
        run: yarn generate:announcement

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(docs): Generated Docs Announcement Bar (automated)'
          base: 'master'
          title: 'chore(docs): Generated Docs Announcement Bar (automated)'
          labels: 'type: chore'
          add-paths: www/docs/**
          branch: 'chore/generate-announcement'
          branch-suffix: 'timestamp'