name: Generate Resources References [Automated]

on:
  pull_request:
    branches:
      - develop
    types:
      - closed
  workflow_dispatch:
    inputs:
      referenceName:
        description: "Reference to Generate. Use either `all` or a name defined in `www/utils/packages/typedoc-generate-references/src/constants/references.ts` such as `product`."
        required: false
        default: "all"

jobs:
  references:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (startsWith(github.head_ref, 'chore/generate-tsdocs') && github.event.pull_request.merged == true)
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: reference

      - name: Build Packages
        run: yarn build

      - name: Install Docs dependencies
        working-directory: www
        run: yarn install

      - name: Install Workspace dependencies
        run: yarn install
        working-directory: www/utils

      - name: Build Workspace dependencies
        run: yarn build
        working-directory: www/utils

      - name: Generate References
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: "yarn start generate ${{ github.event.inputs.referenceName }} --merge"
        working-directory: www/utils/packages/typedoc-generate-references

      - name: Generate References
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: "yarn start generate all --merge"
        working-directory: www/utils/packages/typedoc-generate-references

      - name: Generate Changeset
        run: "yarn generate:changeset"
        working-directory: www/utils/packages/scripts

      - name: Get PR Message
        id: pr-message
        run: yarn generate:message
        working-directory: www/utils/packages/scripts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(docs): Generated References (automated)"
          base: "develop"
          title: "chore(docs): Generated References"
          labels: "type: chore"
          add-paths: |
            www/apps/resources/references/**
            www/apps/resources/generated/**
          branch: "docs/generate-reference"
          branch-suffix: "timestamp"
          body: ${{ steps.pr-message.outputs.body }}
