name: Generate API Reference
on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          token: ${{ secrets.REFERENCE_PAT }}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: reference

      - name: Build Packages
        run: yarn build

      - name: Generate API Reference
        run: yarn openapi:generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore(docs): Generated API Reference'
          base: 'master'
          title: 'chore(docs): Updated API Reference'
          labels: 'type: chore'
          add-paths: docs/api/*
          branch: 'chore/generate-api-ref'
          branch-suffix: 'timestamp'
