name: Generate Public References
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      referenceName:
        description: "Reference to Generate. Use either `all` to generate all references, `api` to generate the API reference, or `ui` to generate UI reference."
        required: false
        default: "all"
  release:
    types: [published]

jobs:
  api-v2:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_call' || github.event.inputs.referenceName == 'all' || github.event.inputs.referenceName == 'api' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REFERENCE_PAT }}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: reference

      - name: Build Packages
        run: yarn build

      - name: Generate API Reference (v2)
        run: yarn openapi:generate

      - name: Install and Build www/utils dependencies
        run: yarn && yarn build
        working-directory: www/utils

      - name: Generate Changeset
        run: "yarn generate:changeset"
        working-directory: www/utils/packages/scripts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(docs): Generated API Reference (v2)"
          base: "develop"
          title: "chore(docs): Updated API Reference (v2)"
          labels: "type: chore"
          add-paths: www/apps/api-reference/specs
          branch: "docs/generate-api-ref"
          branch-suffix: "timestamp"
  ui:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_call' || github.event.inputs.referenceName == 'all' || github.event.inputs.referenceName == 'ui' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REFERENCE_PAT }}
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: reference

      - name: Build Packages
        run: yarn build

      - name: Install Workspace dependencies
        run: yarn install
        working-directory: www/utils

      - name: Build Workspace dependencies
        run: yarn build
        working-directory: www/utils

      - name: Generate UI Specs
        run: yarn generate:ui
        working-directory: www/utils/packages/react-docs-generator

      - name: Generate Changeset
        run: "yarn generate:changeset"
        working-directory: www/utils/packages/scripts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(docs): Generated UI Reference"
          base: "develop"
          title: "chore(docs): Updated UI Reference"
          labels: "type: chore"
          add-paths: www/apps/ui/src/specs
          branch: "docs/generate-ui-ref"
          branch-suffix: "timestamp"
