name: Generate Docblocks [Automated]

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  generate:
    name: Generated TSDoc PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Install www/utils Dependencies
        run: yarn
        working-directory: www/utils

      - name: Build packages
        run: yarn build
        working-directory: www/utils

      - name: Check Commit
        id: check-commit
        run: "yarn check:release-commit ${{ github.sha }}"
        working-directory: www/utils/packages/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Run docblock generator
        if: steps.check-commit.outputs.is_release_commit == 'true'
        run: "yarn start run:release"
        working-directory: www/utils/packages/docblock-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Generate Changeset
        if: steps.check-commit.outputs.is_release_commit == 'true'
        run: "yarn generate:changeset"
        working-directory: www/utils/packages/scripts

      - name: Create Pull Request
        if: steps.check-commit.outputs.is_release_commit == 'true'
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "chore(docs): Generated TSDocs"
          body: "This PR holds all generated TSDocs for the upcoming release."
          branch: "chore/generate-tsdocs"
          add-paths: packages/**
  generate-oas:
    name: Generated OAS PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Install www/utils Dependencies
        run: yarn
        working-directory: www/utils

      - name: Build packages
        run: yarn build
        working-directory: www/utils

      - name: Check Commit
        id: check-commit
        run: "yarn check:release-commit ${{ github.sha }}"
        working-directory: www/utils/packages/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Run docblock generator
        if: steps.check-commit.outputs.is_release_commit == 'true'
        run: "yarn start run ../../../../packages/medusa/src/api --type oas && yarn start clean:oas"
        working-directory: www/utils/packages/docblock-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: medusa

      - name: Create Pull Request
        if: steps.check-commit.outputs.is_release_commit == 'true'
        uses: peter-evans/create-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "chore(docs): Generated OAS"
          body: "This PR holds all generated OAS for the upcoming release."
          branch: "chore/generate-oas"
          add-paths: www/utils/generated/oas-output/**
