name: Generate Entity Reference
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  services:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.20.2"
          cache: "yarn"

      - name: Install dependencies
        uses: ./.github/actions/cache-deps
        with:
          extension: reference

      - name: Build Packages
        run: yarn build

      - name: Generate Entities Reference
        run: yarn generate:entities

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(docs): Generated Entities Reference (automated)"
          base: "develop"
          title: "chore(docs): Generated Entities Reference (automated)"
          labels: "type: chore"
          add-paths: www/apps/docs/content/references/entities/**
          branch: "chore/generate-entities"
          branch-suffix: "timestamp"
